plugins { id 'com.android.application' }
android {
    namespace 'com.aimtd.superapp'
    compileSdk 34
    defaultConfig {
        applicationId "com.aimtd.superapp"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        debug { debuggable true }
        release { minifyEnabled false }
    }
}
